version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app-instance
    environment:
      - IS_LOCAL=true
      - LOCAL_PORT=3000
    volumes:
      - .:/usr/src/app/:rw
    ports:
      - "3000:3000"
    expose:
      - 3000
    command: |
      sh -c '
        if test -d node_modules; \
        then \
          echo node_modules_exists; \
        else \
          cp -a /tmp/node_modules /usr/src/app; \
        fi && \ 
          npm install && npm run start:local'
